### ISSUE TITLE
Does not work on Mac

### ISSUE THREAD

**Issue by vlasy** [AckeeCZ/goproxie#2]
Steps to reproduce:

```
~ ❯ go get -u github.com/AckeeCZ/goproxie
~ ❯ ./go/bin/goproxie
⠉ Loading GCP Projects 2020/02/26 12:42:24 exit status 1
~ ❯
```

**Comment by smoliji** [comment]
There may be the gcloud command failing. We've added the command output @vlasy , give it a try now/

**Comment by vlasy** [comment]
Seems to be fixed in the last release. Thanks
