### ISSUE TITLE
Loading states get stuck on output

### ISSUE THREAD

**Issue by smolijar** [AckeeCZ/goproxie#3]
![image](https://user-images.githubusercontent.com/24388536/75443198-2e32c380-5961-11ea-9823-5e609a839db6.png)
I would expect the following logs to diappear when the phase is done.
```
⠠ Loading Cluster credentials Fetching cluster endpoint and auth data.
⠒ Loading Cluster credentials kubeconfig entry generated for .
```

**Comment by smoliji** [comment]
Should be fixed now 👷
