### ISSUE TITLE
Project is not listed

### ISSUE THREAD

**Issue by smoliji** [AckeeCZ/goproxie#30]
Ive encountered a problem in which I can create a proxy directly - given I know the instance name, but I cannot create it via Goproxie, because the project is not there.
```
cloud_sql_proxy -instances=projectx:europe-west3:databasex=tcp:0.0.0.0:5432
```

Goproxie uses `gcloud projects list` to list projects and `projectx` is not among them.

@sandratatarevicova what do we do? 😱

**Comment by sandratatarevicova** [comment]
From [`gcloud projects list` documentation](https://cloud.google.com/sdk/gcloud/reference/projects/list):

> Lists all active projects, where the active account has Owner, Editor or Viewer permissions. 

I guess you don't have owner, editor nor viewer permission.

**Comment by smoliji** [comment]
Ok. I think I will add an option to add it directly using a new switch `cloud_sql_instance`.

`goproxie -cloud_sql_instance=...`
